name: Test & Build

on:
  pull_requests:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-path: ./package.json
          node-version: 15.5.1

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint
